### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by newpillow** [disposable/disposable#105]
Hi guys, 
My name is Enrique and I'm the owner of newpillow360.com a domain which shows up in the following list: https://github.com/groundcat/disposable-email-domain-list/blob/master/domains.txt
I don't know what happened and why is my domain in that list because I never spammed anyone. Yesterday doing a simple check on the website I installed the VirusTotal extension which sent me the following notification: 1 security vendor flagged this domain as malicious.
Digging through the  notification: https://www.virustotal.com/gui/domain/newpillow360.com/details I found that my domain is listed on this list. 
So, my question is: What happened? Why is my domain flagged as a disposable email domain? 
I checked and double checked my website for malaware, viruses and all that stuff and everything seems ok. Can someone, please, help me with this issue? Thank you.

**Comment by smeinecke** [comment]
Hi, I am sorry to hear this. As we just collect and combine lists, you can check the https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt source map file to find which source lists your domain. 

`https://www.stopforumspam.com/downloads/toxic_domains_whole.txt:newpillow360.com`

I just checked their page and it seems as if some IPs used your domain as sender for spam mails:

https://www.stopforumspam.com/ipcheck/185.104.219.238
https://www.stopforumspam.com/ipcheck/196.196.198.163
https://www.stopforumspam.com/ipcheck/185.104.219.160
https://www.stopforumspam.com/ipcheck/185.104.219.160

They have a removal form https://www.stopforumspam.com/removal which you should check out. As soon as you domain is not listed there anymore, it will be automatically removed from this list aswell.

**Comment by newpillow** [comment]
Ok. Thank you. Have a blessed day!

**Comment by smeinecke** [comment]
Just reopen this issue if this does not work for you and I will check if I can contact them.

**Comment by newpillow** [comment]
Hello, So I used the removal form 2 weeks ago but nothing happened. No answer, no nothing...Any advice on how to manage this?
Thanks
