### ISSUE TITLE
Remove myyahoo.com

### ISSUE THREAD

**Issue by Crmteam-IVG** [disposable/disposable#106]
The domain part "myyahoo.com" is an official domain part by yahoo and can be registered for all users.

Please remove "myyahoo.com" from the disposable list!

**Comment by smeinecke** [comment]
Thank you for the ticket. You're right, the domain is valid and should not be listed as disposable. I just checked our source map:

`https://www.stopforumspam.com/downloads/toxic_domains_whole.txt:myyahoo.com`

I will check why its listed there and try to remove it at the source.
