### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by newpillow** [disposable/disposable#107]
Hi guys,
My name is Enrique and I'm the owner of newpillow360.com a domain which shows up in the following list: https://github.com/groundcat/disposable-email-domain-list/blob/master/domains.txt
I don't know what happened and why is my domain in that list because I never spammed anyone. Yesterday doing a simple check on the website I installed the VirusTotal extension which sent me the following notification: 1 security vendor flagged this domain as malicious.
Digging through the notification: https://www.virustotal.com/gui/domain/newpillow360.com/details I found that my domain is listed on this list.
So, my question is: What happened? Why is my domain flagged as a disposable email domain?
I checked and double checked my website for malaware, viruses and all that stuff and everything seems ok. Can someone, please, help me with this issue?

Hello, So I used the removal form 2 weeks ago, like smeinecke suggested but nothing happened. No answer, no nothing...Any advice on how to manage this?
Thanks

**Comment by smeinecke** [comment]
Not listed anymore.
