### ISSUE TITLE
Disposable SDK [Java SDK Support]

### ISSUE THREAD

**Issue by ZliIO** [disposable/disposable#112]
Hello, I have implemented a simple Java validation tool package. I'm wondering if it's possible to provide it to the project to reduce the integration cost.

Path:  [https://github.com/ZliIO/zliio-disposable](https://github.com/ZliIO/zliio-disposable)

**Comment by smeinecke** [comment]
Thank you very much for your support. I've just added a link to your repository in the main Readme.
