### ISSUE TITLE
nospam.today is giving the script a 403 Forbidden

### ISSUE THREAD

**Issue by flotwig** [disposable/disposable#114]
See the latest run: https://github.com/disposable/disposable-email-domains/commit/090fe4c63009ec43011d0ee037af8f2f1287e8fa

https://nospam.today/home gives the script a 403, but loads fine in a web browser. I wondered if fixing this could be as simple as impersonating a regular browser's `User-Agent` header, but I see the script already does that: https://github.com/disposable/disposable/blob/a8a5ec71fc66e9d7d3c86d1999b8b6d956727c63/.generate#L86

**Comment by copini** [comment]
nospam.today is blocking HTTP/1.1 requests, which Python's urllib uses. Try `curl --head --http1.1 https://nospam.today`, you'll also get a 403.

Modern browsers (and curl by default) use HTTP/2, which urllib doesn't support. Fixing this will probably require migrating to a different HTTP request library...
