### ISSUE TITLE
Emails from temp-mail.org are not blacklisted

### ISSUE THREAD

**Issue by dtirschek** [disposable/disposable#116]
https://temp-mail.org

Got the following example emails:
finixe7104@tipent.com
sifomi3312@v1zw.com
pagama9053@vreaa.com

None of them are in https://github.com/disposable/disposable-email-domains/blob/master/domains.txt

**Comment by dtirschek** [comment]
Some digging:

`POST https://web2.temp-mail.org/mailbox` should be possible to crawl. I tested a couple times. It blocks the Request, when User-Agent is missing, otherwise it gives a response in this format:

```json
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZDhkMmM1N2U2YjEyNDgyOWI4MDdkNDQ5MWNiZmZmYWUiLCJtYWlsYm94Ijoiaml2YWxpNjc0NkByb3lhbGthLmNvbSIsImlhdCI6MTY5MTQxNDQ4NX0.u6cg4kmhf6ceUg84LxV3SMeJxh8Q3k-z4HWeKbMbRsU",
    "mailbox": "jivali6746@royalka.com"
}
```

Token can be used in subsequent requests to call the same endpoint path with `GET` with the bearer token set.

**Comment by smeinecke** [comment]
included via https://github.com/7c/fakefilter
