### ISSUE TITLE
Remove benilde.edu.ph from disposable domains list

### ISSUE THREAD

**Issue by jacobcat** [disposable/disposable#128]
benilde.edu.ph is a bonafide, non-disposable domain from De La Salle-College of Saint Benilde in Manila, Philippines, and as such, should be removed from this list.

**Comment by smeinecke** [comment]
I checked https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt and the domain "benilde.edu.ph" is listed on https://www.stopforumspam.com/downloads/toxic_domains_whole.txt - please check on their page aswell why the domain got listed / how to remove it there aswell.
