### ISSUE TITLE
Please remove from purple.dev from disposable email domain list

### ISSUE THREAD

**Issue by christo0smal** [disposable/disposable#129]
Good day

Our domain, purple.dev is not a domain used for temporary emails. Request if if could please be removed from the list.

Thanks
Christo

**Comment by smeinecke** [comment]
Please check https://raw.githubusercontent.com/disposable/disposable-email-domains/af268ba1f221cc759694d41ec48addcd246f7a95/domains_source_map.txt as the domain is listed on multiple lists.

**Comment by christo0smal** [comment]
Good day
I don't know what this means. Could you kindly explain to me? How do I get my domain removed from the lists?

**Comment by smeinecke** [comment]
This project only aggregates several external sources to offer them as a combined list - only very few entries on this list are from sources we are scraping ourselves. 

If you search for your domain in the .txt file (which lists from which source which domain in our list originates), you will find all URLs/Lists on which this domain is listed.

As we only combine these lists, but have no influence on the content of it, you have to contact the maintainers of the lists directly to have the domain removed. 

* https://github.com/FGRibreau/mailchecker/
* https://github.com/ivolo/disposable-email-domains/
* https://github.com/wesbos/burner-email-providers/

I think the best way is to create a pull request or issue to the above mentioned repositories to remove the domain from the corresponding list. Afterwards your domain should be automatically removed from this list.
