### ISSUE TITLE
Remove angi.com

### ISSUE THREAD

**Issue by naveen-browserstack** [disposable/disposable#133]
This domain is no more a disposable domain and is a valid domain now. Refer - https://www.angi.com/angies-list
Also the email provider is Google.

**Comment by smeinecke** [comment]
The domain is listed on multiple lists - please check https://raw.githubusercontent.com/disposable/disposable-email-domains/af268ba1f221cc759694d41ec48addcd246f7a95/domains_source_map.txt

Please check that other sources too.
