### ISSUE TITLE
Remove cbamboo.com

### ISSUE THREAD

**Issue by dan-cbamboo** [disposable/disposable#134]
This is the domain for my company, and it's not disposable. Please remove it from the list.

**Comment by smeinecke** [comment]
Thank you for your issue. We only collect other sources and map them into a full list. Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/af268ba1f221cc759694d41ec48addcd246f7a95/domains_source_map.txt) on 

https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json:cbamboo.com

Please create a PR on https://github.com/ivolo/disposable-email-domains too.
