### ISSUE TITLE
SimpleLogin domains marked in your disposable emails list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [disposable/disposable#136]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. To be more precise, dralias.com, 8alias.com, 8shield.net, slmail.me, are included. 

I can see that there have been issues created for this in the past, but would like to make it known that, at Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list. 

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by smeinecke** [comment]
Correct, we already discussed this in #81. 

Currently I'm not really sure how to proceed with the issue, as we have already (albeit rather by accident) currently enabled mozmail.com (see #97). 

I'm thinking of adding a flag in the generator and the aliases domains separately, so that they can still be rejected, if desired by the webmaster.

**Comment by smeinecke** [comment]
I've extended the current script to generate a "strict" list which does include services like proton, duck and mozmail. Its not enabled by default and will be exported as dedicated list. On next update (in ~6h) the domains should be removed from the normal list.

**Comment by groovecoder** [comment]
> I can see that there have been issues created for this in the past, but would like to make it known that, at Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list.

I work on Firefox Relay - the service that creates mozmail.com email masks. We also take anti-abuse seriously and are active participants in m3aawg.org. We would also like to work with you on having our domain removed from even the "strict" list.
