### ISSUE TITLE
duck.com

### ISSUE THREAD

**Issue by astroblaster** [disposable/disposable#137]
Hello,

I'm writing as a postmaster for duck.com, DuckDuckGo's email forwarding service.

It seems we've landed on your list as a disposable email.   We don't intend for our service to be used as a disposable email. We take any reports of abuse seriously.   Would you consider removing this entry?

Thank you,

Brian Kowalewicz

**Comment by smeinecke** [comment]
Please see #136 - I will decide in the next few weeks how to proceed.
