### ISSUE TITLE
Daily updated repository stopped working and solution

### ISSUE THREAD

**Issue by tvr121** [disposable/disposable#139]
The daily updated repository already stopped working and now not updating for months. 

After some testing, I found that changing line 446 of the .generate file to the following line solved the issue.

for (ky, vl) in res.headers.items():

Also I had to disable mail-temp.com as it was getting stucked. Please the project. Thanks.

**Comment by smeinecke** [comment]
Hi, first of all. thank you for your bugreport. You're right, after the change to httpx as HTTP client this some was broken. I'll test this and release an updated version.

**Comment by smeinecke** [comment]
Updated - https://github.com/disposable/disposable-email-domains/commit/af268ba1f221cc759694d41ec48addcd246f7a95

I probably have to fix some sources as they are not reachable from the update server.

**Comment by tvr121** [comment]
Thank you very much for the quick action. Really appreciate this.
