### ISSUE TITLE
Update whitelist

### ISSUE THREAD

**Issue by ghost** [disposable/disposable#142]
@smeinecke according to https://github.com/disposable/disposable/commit/7359b94ab395be74dd2b701cfe12f005fe06248c (tutanota witelisting) I ask you to whitelist Proton domain too:

```
protonmail.ch
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
simplelogin.co
simplelogin.io
```

Otherwise it is looking like some kind of discrimination :(

**Comment by Igyduhkctd** [comment]
@smeinecke please take a look

**Comment by smeinecke** [comment]
See #136
