### ISSUE TITLE
Please delist tmxnet.com, my personal/business email domain of 25 years, not a disposable domain

### ISSUE THREAD

**Issue by rsteph22** [disposable/disposable#156]
A few days ago, Trimble would not allow me to sign up for their service with my tmxnet.com email address. After being put in touch with their I.T. people, was told that they validate their signup form with your list. Upon checking, I found my domain on your following lists:

domains.txt
domains_strict.txt
domains_mx.txt

I have owned the tmxnet.com domain since 1999, and have run my own web and email server under that domain name since the early 2000s for both personal and business use. The only email that originates from that domain are from me, and two immediate family members. With the exception of a compromised formmail script nearly two decades ago,, there has never been any abuse of any sort - email or otherwise - originating from that domain, or any other domain under my control.

Please delist tmxnet.com at your first opportunity. I would be happy to provide any additional info you might require to facilitate the delisting.

Thank you,

**Comment by smeinecke** [comment]
Thank you for your issue. We only collect other sources and map them into a full list. Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt ) on 

https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json

Please create a PR on https://github.com/ivolo/disposable-email-domains too.

**Comment by rsteph22** [comment]
Good evening,

Thanks for the quick response and additional info. heading over there 
now.

-Bob

On 2024-02-08 15:50, Stefan Meinecke wrote:

> Thank you for your issue. We only collect other sources and map them 
> into a full list. Your domain is is listed (see 
> https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt 
> ) on
> 
> https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json
> 
> Please create a PR on https://github.com/ivolo/disposable-email-domains 
> too.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/disposable/disposable/issues/156#issuecomment-1934911738
[2]

**Comment by smeinecke** [comment]
Your domain has been included in our allow list, and the public list has been revised accordingly, ensuring it's no longer listed (at least from our end). However, due to recurring false positives from the source, I believe we need to deactivate it. It appears that the administrator of the ivolo list is not attending to new tickets.

**Comment by rsteph22** [comment]
Hello Stefan,

When I left the message @ the Ivolo list, I saw how old some of the 
other requests were and thought uh-oh. I'm glad you saw that.

At any rate, thanks kindly for getting tmxnet.com sorted on your list. 
Greatly appreciated.

-Bob

On 2024-02-08 18:49, Stefan Meinecke wrote:

> Your domain has been included in our allow list, and the public list 
> has been revised accordingly, ensuring it's no longer listed (at least 
> from our end). However, due to recurring false positives from the 
> source, I believe we need to deactivate it. It appears that the 
> administrator of the ivolo list is not attending to new tickets.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/disposable/disposable/issues/156#issuecomment-1935108188
[2]
