### ISSUE TITLE
lionelastomers.com is not a disposable domain

### ISSUE THREAD

**Issue by lionelastomers** [disposable/disposable#166]
To whom it may concern:

lionelastomers.com is on your list of disposable domains, but it is not.  What do we need to do to get our company name removed from this list?

**Comment by smeinecke** [comment]
Hi!

Thank you for your feedback. We only collect other sources and map them into a full list. Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt ) on

https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.txt
https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

Please contact stopforumspam.com and https://github.com/FGRibreau/mailchecker for more informations / to remove your domain there aswell. I will add your domain to our allowlist. It should be removed on next update of our static list.

Cheers
