### ISSUE TITLE
lilo.org is a legit domain, not a disposable domain

### ISSUE THREAD

**Issue by KayessFR** [disposable/disposable#167]
Hi, the domain **lilo.org** is a legit domain, not a disposable one. I can't use my email on certain website because of that.
Could someone please remove it from the list? Thanks !

**Comment by smeinecke** [comment]
Hi!

Thank you for your feedback. We only collect other sources and map them into a full list. Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt ) on

https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

Please contact stopforumspam.com for more informations. I will add your domain to our allowlist. It should be removed on next update of our static list.

Cheers,

Stefan
