### ISSUE TITLE
zoho.com is not disposable

### ISSUE THREAD

**Issue by williamdes** [disposable/disposable#170]
zoho.com is not disposable

There is also zoho.in but I do not know about this tld. But I used Zoho and they are a normal company.

**Comment by fnetX** [comment]
I second this. This is causing disruption for many users who use zoho.com, and we never encountered unwanted visits from this source.

**Comment by mtmail** [comment]
I created a [PR](https://github.com/disposable/disposable/pull/178) now. zohomail.com, their email product, isn't on the disposable list so I don't see why zoho.com should be. Corporate email address for example is support@zoho.com

Source was `https://www.stopforumspam.com/downloads/toxic_domains_whole.txt:zoho.com`
