### ISSUE TITLE
deity.co.nz is not a disposable email domain

### ISSUE THREAD

**Issue by nullpainter** [disposable/disposable#176]
I have owned this domain for years now, however it is somehow now present on https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json 

It's a personal, not a disposable domain.

This appears to be a recent change. I use https://forwardemail.net/ for email forwarding and this stopped yesterday evening due to `deity.co.nz` being on a blocklist.

**Comment by nullpainter** [comment]
I raised an issue with https://github.com/wesbos/burner-email-providers/ as this appears to be the source.

**Comment by smeinecke** [comment]
Add to whitelist. https://github.com/disposable/disposable/commit/47469f694ad90f40682cfee29a250e79a331022d 

thanks for the ticket https://github.com/wesbos/burner-email-providers/issues/459
