### ISSUE TITLE
Requesting removal of Kennedy808.com from the list of temp email domains.

### ISSUE THREAD

**Issue by MegaDude808** [disposable/disposable#190]
Hello, Kennedy808.com is my personal email domain. It is not associated with a temp email service of any kind.

Here's an image showing the domain as an alias in my Google Workspace account. Let me know if there's any other proof you need.

Thanks for your help.

<img width="1410" alt="domains" src="https://github.com/user-attachments/assets/c274dbf2-29d0-4469-9b74-15466dec8f99">

**Comment by smeinecke** [comment]
We are just an aggregator of lists and do not manage the sourcing itself.

Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt ) on

- https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json
- https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt
- https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.txt

Please open a ticket on the github repositories to remove your domain from their list.

**Comment by MegaDude808** [comment]
Got it, I'll reach out to them.
