### ISSUE TITLE
buildingradar.com is not a disposable email domain

### ISSUE THREAD

**Issue by frozturk** [disposable/disposable#192]
buildingradar.com should be removed from the list.

https://buildingradar.com/
https://verifymail.io/domain/buildingradar.com

**Comment by frozturk** [comment]
@smeinecke how can we proceed with this?

**Comment by smeinecke** [comment]
@frozturk We are just an aggregator of lists and do not manage the sourcing itself.

Your domain is is listed (see https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt ) on

https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

Please open a thread on www.stopforumspam.com to remove your domain from their list.

**Comment by frozturk** [comment]
Thanks 👍
