### ISSUE TITLE
Additional Domains

### ISSUE THREAD

**Issue by hqhow** [disposable/disposable#48]
Hello,

I want to add this email list to your list.

> @exam365.edu.vn
> @cvbuilder365.com
> @findexpert365.com
> @au2post.com
> @okchat365.com
> @gendoc24h.com
> @trigger365.com
> @121projects.com

This is a manual collection so I can't give you dynamic DB, I will try to do the automatically source API so you can update it regularly later.

**Comment by mflash123** [comment]
+
@donmah.com

**Comment by smeinecke** [comment]
Sorry for my late reply. 

I am sorry, but we do not add domains to the list without proof of source or activity. 

Unfortunately, we have already had the problem in the past that a domain was reported which was only intended to be damaged, but did not offer a disposable email service.

What is striking about hqhow's list is that all the domains mentioned are hosted by the same provider who offers CMS.

@mflash123 Unfortunately, I have not yet found a direct source of the domain, but there are many bots that use this domain as an email. I will get back to you on this.

**Comment by mflash123** [comment]
> Sorry for my late reply.
> 
> I am sorry, but we do not add domains to the list without proof of source or activity.
> 
> Unfortunately, we have already had the problem in the past that a domain was reported which was only intended to be damaged, but did not offer a disposable email service.
> 
> What is striking about hqhow's list is that all the domains mentioned are hosted by the same provider who offers CMS.
> 
> @mflash123 Unfortunately, I have not yet found a direct source of the domain, but there are many bots that use this domain as an email. I will get back to you on this.

Thanks for replay.
My Prof:[ https://temp-mail.org/ru/]( https://temp-mail.org/ru/)

**Comment by smeinecke** [comment]
ah, thanks. I will check why our local temp-mail.org implementation did not add that domain. could be that I have to add some kind of scraping service for that service host.

**Comment by smeinecke** [comment]
Added in fa697af6aeec591203b821e1cec178fca3102764
