### ISSUE TITLE
Name Server Check

### ISSUE THREAD

**Issue by Prajwal-Koirala** [disposable/disposable#53]
```
Hello;
Can someone add a name server check and validate all the domains on the list.
- prajwal
```

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/disposable-services

**Comment by Prajwal-Koirala** [comment]
More than 50% of the domains here don't even have a NS;
SPF Checks.

**Comment by smeinecke** [comment]
That feature is already implemented ;)
Parameter --dns-verify on client. 

Or use list from https://github.com/disposable/disposable-email-domains/blob/master/domains_mx.txt
