### ISSUE TITLE
Domain error?

### ISSUE THREAD

**Issue by mluboroscev** [disposable/disposable#58]
Hello,

in file "https://raw.githubusercontent.com/andreis/disposable-email-domains/master/domains.txt" domain "pradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.orgpradajapan.org" is error?

**Comment by smeinecke** [comment]
Thanks for the info. you're right, this is probably a bug in the import script. Will check that this weekend.

**Comment by smeinecke** [comment]
Problem is in one of the source, just opened a ticket on https://github.com/wesbos/burner-email-providers/issues/269

Will add a regex check for valid domain names to filter them.

**Comment by mluboroscev** [comment]
Hello. Again this problem.
