### ISSUE TITLE
Additional domains by temp-mail

### ISSUE THREAD

**Issue by whoacowboy** [disposable/disposable#59]
https:// temp - mail . org/en/

@hype68.com
@iludir.com
@gridmire.com
@laraskey.com

I found if you use postman to ping this url (using spaces to hide from search)

https:// web1. temp - mail . org/request/domains/format/json

it will return their latest urls.

[
    "@gridmire.com",
    "@hype68.com",
    "@iludir.com",
    "@laraskey.com"
]

**Comment by smeinecke** [comment]
I am sorry but they disabled that API endpoint a while ago. They switched to a new endpoint, but I am not aware how to automatically requests the domain list as they use cloudflare and any request done by a normal URL call is blocked.

**Comment by smeinecke** [comment]
Added in fa697af6aeec591203b821e1cec178fca3102764
