### ISSUE TITLE
Hubspot list contains too many non-disposable domains

### ISSUE THREAD

**Issue by mtmail** [disposable/disposable#77]
The Hubspot list added in https://github.com/disposable/disposable/commit/2205c212b56b9c7651b306904c623b3d00a555d0 contains a lot of valid domains.

Examples: gmail.com, googlemail.com, outlook.com, me.com (Apple), icloud.com, zoho.com. Most international yahoo, hotmail, outlook, live (Microsoft).

It matched my own private email which I pay for. And matched a dozen of my paying customers.

It might be a list of free email providers but it conains too many non-disposable domains.

Entries like calendar-server.bounces.google.com, doclist.bounces.google.com also seem to belong to different spam lists, not a disposable domain list.

**Comment by smeinecke** [comment]
Thanks for pointing that out. I somehow overlooked this and added the list more or less unchecked. It's removed in the repository and I just triggered the static export to remove it on https://github.com/disposable/disposable-email-domains aswell.
