### ISSUE TITLE
Whitelist legitimate email aliasing servicess

### ISSUE THREAD

**Issue by paulverbeke** [disposable/disposable#81]
I see that in the production list of 137k domains there is the domains associated with https://simplelogin.io/ 
![image](https://user-images.githubusercontent.com/6412153/172344286-53ab18c0-d31e-4434-9027-3e79caacb198.png) and https://anonaddy.com/ which are legitimate aliasing services that help to protect our privacy and security by using unique email for each and every account created online.
It's the same recommendation than using unique password for every account. By the way these services are currently being directly integrated into popular password manager like Bitwarden and 1Password. So in the end, having these domains flagged/banned wordwild will be detrimental to end users.

**Comment by r8u** [comment]
I personally think there should be two lists then, because allowing aliasing services isn't that great if you want to block 'disposable-type' emails.

**Comment by smeinecke** [comment]
The problem is that we can't categorize the domains, because we mostly just combine already existing lists. 

From these lists, it is not clear how or where this domain was listed / which service uses this domain.

**Comment by paulverbeke** [comment]
That's why I'm talking about having a whitelist of domains related to legitimate aliasing services. 
These are legitimate and registered companies so the domains should be relatively constant or at worst manageable to follow with merge requests. These companies are for profit so with a fee to pay (or at worst in a limited freemium model that is protected from abuse on their end) so this fact should provide incentive/protection enough against spam.
When aggregating/combining lists this project should skip whitelisted domains. That way this project stay useful to avoid spam and false users but allow user that seek privacy.

**Comment by smeinecke** [comment]
Unfortunately, I have to admit that from a website operator's point of view, I don't see any difference between this service and any other DEA. The user provides an email address during registration, which is created "temporarily" and can be removed within seconds.

See: https://simplelogin.io/docs/getting-started/one-click-unsubscribe/ 
"All forwarded emails from SimpleLogin provide this one-click unsubscribe button that allows you to stop receiving these emails by clicking on it, which will disable the alias. "
So here simplelogin even explicitly advises to rather disable the alias directly instead of actively unsubscribing from a service. This shows exactly the problem.

You are welcome to create an allow-list and maintain it. Unfortunately I don't have the capacity to maintain this manually.

However, I am willing to refer to your list in the README and will gladly include an option in the generator to activate this allow-list.

**Comment by jasonkarns** [comment]
The distinction is about length of operation. Disposability is about the registrant creating an address that is _from the beginning_ intent on being short-lived. (Though I understand that intent isn't necessarily something that can be checked automatically.)

Aliased addresses are not (at the time of creation) intended to be temporary but rather exist to safeguard one's "real" address. In that respect, they are no more disposable than the "real" address, which can also be discarded with a new address "created in seconds from free providers".

The _ease_ of creating aliases or dropping them is not a distinguishing factor for what determines disposability. A user who simply stops logging into a "permanent" hotmail account is similarly "disposing of their address in seconds".

Thus it's left really to heuristics to determine if a service's intended use is for temporary or long-term aliasing. Simplelogin (like apple's own icloud HideMyEmail) is clearly intended for long-term aliasing. The one-click dropping is to guard against when website operators sell/share their address list or are leaked.

**Comment by smeinecke** [comment]
I will decide in the next few weeks how to proceed - see #136 .

**Comment by rafalkrupinski** [comment]
> See: https://simplelogin.io/docs/getting-started/one-click-unsubscribe/
> "All forwarded emails from SimpleLogin provide this one-click unsubscribe button that allows you to stop receiving these > emails by clicking on it, which will disable the alias. "
> So here simplelogin even explicitly advises to rather disable the alias directly instead of actively unsubscribing from a service. This shows exactly the problem.

`One-click unsubscribe - Commercial mail must have the one-click unsubscribe functionality as described in [RFC 8058](https://datatracker.ietf.org/doc/html/rfc8058)`

https://www.m3aawg.org/blog/SendingBulkMailToGmail_Yahoo
https://datatracker.ietf.org/doc/html/rfc8058



Might as well disable the whole SMTP.
