### ISSUE TITLE
Domain uescort.com wrongfully added 

### ISSUE THREAD

**Issue by gdluck** [disposable/disposable#91]
This is not a disposable domain, please remove it.

**Comment by smeinecke** [comment]
Thanks for the note. We do not manage any lists, this just collects entries from other lists and merges them into one giant list. The Domain is imported from https://github.com/FGRibreau/mailchecker/.

You probably want to open an Issue there https://github.com/FGRibreau/mailchecker/issues to remove the domain.

**Comment by smeinecke** [comment]
Just as note on our side - Issue at source: https://github.com/FGRibreau/mailchecker/issues/398
