### ISSUE TITLE
Add: Simplelogin.com

### ISSUE THREAD

**Issue by Fossil01** [disposable/disposable#95]
https://simplelogin.io/

Has many aliases. Here's a few:

simplelogin.com
simplelogin.io
simplelogin.fr
aleeas.com
8alias.com
dralias.com
slmail.me
8shield.net

If someone has an account there they might be able to provide the full list: https://simplelogin.io/docs/custom-domain/manage-domain/

**Comment by jasonkarns** [comment]
Simplelogin is an alias, not temporary or disposable. Like apple's own Hide My Email

**Comment by smeinecke** [comment]
Duplicate of #86.
